<div style="background: #000;
            color: #FFF;
            margin: 0px;
            padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1>Week 24 Lab</h1>
</div>


### By Juan Peralta

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## Part 1 - Python Problems
<hr>

### Exercise 1

Create a function that takes a list of integers and calculates the mean. Use the following formula for calculating averages and not any `mean`/`average` method.

$$ \mu = {\frac {1}{n}}\sum _{i=1}^{n}a_{i}={\frac {a_{1}+a_{2}+\cdots +a_{n}}{n}}$$

In [3]:
example_list = [1,2,3,4,5,6,7,8,9]
sum = 0
for idx, val in enumerate(example_list):
    sum += val
mean_result = sum/len(example_list)
print('The mean is ', mean_result)

The mean is  5.0


### Exercise 2

Create a class that operates like a stack.  

In [4]:
class Stack():
    def __init__(self, arr = []):
        self.arr_list = arr
    
    def push(self, val):
        self.arr_list.append(val)
    
    def pop(self):
        if len(self.arr_list)>1:
            pop_val = self.arr_list[-1]
            self.arr_list = self.arr_list[0:-1]
            return pop_val
        else:
            return 'Stack Underflow'
    
    def display_stack(self):
        print(self.arr_list)

st = Stack([1,2])

#Push
st.push(3)
st.display_stack()

#Pop
print(st.pop())
st.display_stack()

[1, 2, 3]
3
[1, 2]


### Exercise 3

Write a generator function which returns a few values and then use it to retrieve a value using `next` (the global function). 

In [5]:
# Generating Fibonacci Numbers 
def fibonacci_generator(limit): 
    # Initialize first two Fibonacci Numbers
    a, b = 0, 1
    
    #First return few values
    yield a,b
    
    # One by one yield next Fibonacci Number
    while b < limit:
        a, b = b, a + b
        yield b

# Create a generator object 
x = fibonacci_generator(6)

# First, return first 2 values of fibonacci seies
print('Yielding first two numbers')
print(x.__next__())

# Using "next" for further values 
print('Yielding further values using next')
print(x.__next__()) 
print(x.__next__()) 
print(x.__next__()) 
print(x.__next__()) 


Yielding first two numbers
(0, 1)
Yielding further values using next
1
2
3
5


### Exercise 4

Create a namedtuple `'Point'` that contains the points `x` and `y`.

In [8]:
x = 10,
y = 20
Point = (x,y)

### Exercise 5

Create a moving average class that:
* has a method `add` that is used to add new values
* has a method `avg` that calculates the average of the 5 most recently added values
* has an attribute `values` that contain all values added
* has an attribute `window` that contains the 5 most recently added values

In [9]:
class moving_avg():
    
    def __init__(self,values = []):
        self.values = values
        self.window = self.values[-5:]
    
    def add(self, new_value):
        self.values.append(new_value)
        self.window = self.values[-5:]
    
    def avg(self):
        self.Sum = 0
        for idx,val in enumerate(self.window):
            self.Sum+=val
        self.Mean = self.Sum/5
        self.Sum = 0
        return self.Mean

#Create Object with some values and find moving average
ma = moving_avg([1,2,3,4,5])
print(ma.avg())

#Add more value and find moving average
ma.add(6)
print(ma.avg())

3.0
4.0


## Part 2 - Numpy Problems
<hr>

### Exercise 1

Using numpy, create an array that contains the values of $y$ for each of the $x$ values ranging from 0 to 100.

$$ y = 12x+4  $$

In [10]:
x = np.arange(0,101,1)
y = 12*x +4
y

array([   4,   16,   28,   40,   52,   64,   76,   88,  100,  112,  124,
        136,  148,  160,  172,  184,  196,  208,  220,  232,  244,  256,
        268,  280,  292,  304,  316,  328,  340,  352,  364,  376,  388,
        400,  412,  424,  436,  448,  460,  472,  484,  496,  508,  520,
        532,  544,  556,  568,  580,  592,  604,  616,  628,  640,  652,
        664,  676,  688,  700,  712,  724,  736,  748,  760,  772,  784,
        796,  808,  820,  832,  844,  856,  868,  880,  892,  904,  916,
        928,  940,  952,  964,  976,  988, 1000, 1012, 1024, 1036, 1048,
       1060, 1072, 1084, 1096, 1108, 1120, 1132, 1144, 1156, 1168, 1180,
       1192, 1204])

### Exercise 2

Create a 2-dimensional numpy array that contains the numbers from 1 to 20 with even numbers in the first column and odd numbers in the second.

In [12]:
a = np.arange(1,21,1)
a = a.reshape(10,2)
np.append(a[:,1].reshape(10,1),a[:,0].reshape(10,1),1)

array([[ 2,  1],
       [ 4,  3],
       [ 6,  5],
       [ 8,  7],
       [10,  9],
       [12, 11],
       [14, 13],
       [16, 15],
       [18, 17],
       [20, 19]])

### Exercise 3

Create a numpy array with random numbers between 0 and 1.

In [13]:
#Generating 10 numbers in the range [0.0 , 1.0)
np.random.random_sample((10,))

array([0.19179252, 0.02524043, 0.0329258 , 0.29646688, 0.6732637 ,
       0.34300414, 0.40088511, 0.66444048, 0.62459456, 0.95989168])

### Exercise 4

Create an array that contains 100 numbers. All of them between 0 and 5. Then add that to an array that contains the numbers from 0 to 99.

In [19]:
a= np.random.randint(low = 0, high = 5, size = (100,))
b= np.arange(0,100)
result = a+b

In [20]:
result

array([  4,   4,   6,   3,   5,   8,  10,   7,  12,   9,  12,  13,  14,
        15,  18,  15,  18,  20,  20,  22,  22,  22,  25,  26,  24,  27,
        29,  29,  29,  32,  32,  34,  32,  35,  37,  37,  36,  39,  38,
        39,  42,  41,  45,  45,  47,  49,  49,  51,  49,  53,  54,  55,
        56,  54,  56,  55,  60,  58,  60,  60,  63,  64,  62,  65,  66,
        68,  67,  67,  68,  70,  72,  72,  74,  76,  78,  79,  77,  79,
        81,  81,  83,  85,  85,  85,  88,  86,  88,  88,  89,  89,  93,
        93,  93,  95,  96,  97,  97,  99, 100, 102])

### Exercise 5

Create a 10 by 10 matrix containing zeros. Then create a 10 by 10 matrix containing ones. Combine the two matrices so that the new dimensions are 20 by 10.

In [21]:
mat_zero = np.zeros((10,10))
mat_one = np.ones((10,10))
result = np.vstack((mat_zero, mat_one))
result

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

### Exercise 6

Given the following numpy array, find the cumulative sum along the rows. Then find the cumulative sum along the columns. Then output the 2nd (1st index) column but only the first 10 rows. You should get a very recognizable pattern.

In [22]:
a = np.array([[0,1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10,0], [2,3,4,5,6,7,8,9,10,0,1], [3,4,5,6,7,8,9,10,0,1,2],[4,5,6,7,8,9,10,0,1,2,3],[5,6,7,8,9,10,0,1,2,3,4],[6,7,8,9,10,0,1,2,3,4,5],[7,8,9,10,0,1,2,3,4,5,6],[8,9,10,0,1,2,3,4,5,6,7],[9,10,0,1,2,3,4,5,6,7,8],[10,0,1,2,3,4,5,6,7,8,9]])
#Calculate cumulative sum along rows
c_sum_row = np.cumsum(a, axis = 1).reshape(11,11)
c_sum_col = np.cumsum(c_sum_row, axis = 0).reshape(11,11)

# Print the required portion
c_sum_col[:10,1]

#Resulting numbers are squares of first 10 natural numbers

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

### Exercise 7

Using the following string. Turn it into a numpy array where all the letters are their own element.

In [14]:
s = "helloworld"
print(np.asarray(list(s)))

['h' 'e' 'l' 'l' 'o' 'w' 'o' 'r' 'l' 'd']


### Exercise 8

How would we flatten the following array?

In [24]:
a = np.eye(10)
print(a.flatten())

[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 1.]


## Part 3 - Pandas Problems
<hr>

**1.** Create a dataframe using the following:

In [16]:
lst = [['Red',4],['Blue',6],['Green',1],\
       ['Yellow',5],['White',3],['Black',2],]


In [17]:
df = pd.DataFrame(lst)
df

0  1
0     Red  4
1    Blue  6
2   Green  1
3  Yellow  5
4   White  3
5   Black  2

**2.** Create a dataframe using the following:

In [18]:
dct = {'red':4, 'blue':6, 'green':1,\
       'yellow':5, 'white':3, 'black':2 }

In [19]:
df = pd.DataFrame.from_dict(dct.items())
df

0  1
0     red  4
1    blue  6
2   green  1
3  yellow  5
4   white  3
5   black  2

**The following exercises will use the dataset imported below:**


In [20]:
df = pd.DataFrame([[np.nan,'Toyota','Camry',336978, 24765,np.nan],[2019,'Toyota','Corolla',304850, np.nan,4560556],[2019,'Toyota','Supra',np.nan, 35545,102511.78],[2019,np.nan,'Avalon',np.nan ,36480,1012940.16]])
df.columns = ['year', 'make', 'model', 'number sold', 'price', 'revenue (in thousands)']
df

year    make    model  number sold    price  revenue (in thousands)
0     NaN  Toyota    Camry     336978.0  24765.0                     NaN
1  2019.0  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019.0  Toyota    Supra          NaN  35545.0               102511.78
3  2019.0     NaN   Avalon          NaN  36480.0              1012940.16

### Exercise 4

Fix the `year` column in the dataframe by replacing missing values with the average value of that column.

In [21]:
#Find mean year
mean_year = df['year'].mean()

#Impute
df['year'] = df['year'].fillna(mean_year)
df

year    make    model  number sold    price  revenue (in thousands)
0  2019.0  Toyota    Camry     336978.0  24765.0                     NaN
1  2019.0  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019.0  Toyota    Supra          NaN  35545.0               102511.78
3  2019.0     NaN   Avalon          NaN  36480.0              1012940.16

### Exercise 5

Fix the `'make'` column by replacing the missing value with the value that occurred most frequently (mode).

In [22]:
#Find mode of make column
mode_value = df['make'].mode()[0]

df['make'] = df['make'].fillna(mode_value)
df

year    make    model  number sold    price  revenue (in thousands)
0  2019.0  Toyota    Camry     336978.0  24765.0                     NaN
1  2019.0  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019.0  Toyota    Supra          NaN  35545.0               102511.78
3  2019.0  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 6

Fix the `'revenue (in thousands)'` column by calculating the approximate revenue. Remember that the value of `'revenue'` is in the 1000s.

$$ \textrm{revenue} = \textrm{number sold} * \textrm{price} $$

In [23]:
df['revenue (in thousands)'] = df['revenue (in thousands)'].fillna(df['number sold']* df['price']/1000)
df

year    make    model  number sold    price  revenue (in thousands)
0  2019.0  Toyota    Camry     336978.0  24765.0              8345260.17
1  2019.0  Toyota  Corolla     304850.0      NaN              4560556.00
2  2019.0  Toyota    Supra          NaN  35545.0               102511.78
3  2019.0  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 7

Fix the `'price'` column by calculating the approximate price.

$$ \textrm{price} = \frac{\textrm{revenue}}{\textrm{number sold}} $$

In [24]:
df['price'] = df['price'].fillna((df['revenue (in thousands)']*1000)/df['number sold'])

In [25]:
df

year    make    model  number sold    price  revenue (in thousands)
0  2019.0  Toyota    Camry     336978.0  24765.0              8345260.17
1  2019.0  Toyota  Corolla     304850.0  14960.0              4560556.00
2  2019.0  Toyota    Supra          NaN  35545.0               102511.78
3  2019.0  Toyota   Avalon          NaN  36480.0              1012940.16

### Exercise 8

Fix the `'number sold'` column by calculating the approximate number of vehicles sold.

$$ \textrm{number sold} = \frac{\textrm{revenue}}{\textrm{price}} $$

In [26]:
df['number sold'] = df['number sold'].fillna((df['revenue (in thousands)']*1000)/df['price'])
df

year    make    model  number sold    price  revenue (in thousands)
0  2019.0  Toyota    Camry     336978.0  24765.0              8345260.17
1  2019.0  Toyota  Corolla     304850.0  14960.0              4560556.00
2  2019.0  Toyota    Supra       2884.0  35545.0               102511.78
3  2019.0  Toyota   Avalon      27767.0  36480.0              1012940.16