<div style="background: #000;
            color: #FFF;
            margin: 0px;
                padding: 10px 0px 20px 0px;
            text-align: center; 
                ">
    <h1 style="padding: 2220px 210px -30px 0px;">Week 14 Lab</h1>
</div>

### By Juan Peralta

In [24]:
# imports
import numpy as np

## Exercise 1

Create the following numpy arrays:
    
a) An array using the following lists (make it interesting if you can)

In [14]:
# a = np.array([1,2,3,4,5,6])
l = [0,0,0,0,0] 
m = [1,2,3,4,5]
arr = np.array(l+m)
arr

array([0, 0, 0, 0, 0, 1, 2, 3, 4, 5])

b) A 3 x 4 matrix of zeros: 

In [104]:
#[np.zeros(3), np.zeros(4)]

np.zeros((3,4))


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

c) A 2 x 4 matrix of zeros and ones of the following format:

[[0,0,1,1], [0,0,1,1]]

(try without using python lists)

In [109]:
#arr0z = np.zeros((2,4))

size = (2,2)
zeros = np.zeros(s)
ones = np.ones(s)
#output = np.hstack((zeros,ones))
output = np.concatenate((zeros,ones), axis=1)

#print(arr0z)
print('\n','Ones of the following format:[0,0,1,1, 0,0,1,1]','\n')
print(output)



 Ones of the following format:[0,0,1,1, 0,0,1,1] 

[[0. 0. 1. 1.]
 [0. 0. 1. 1.]]


e) A 3 x 4 array from the following numpy array (do not change the already existing code):

In [112]:
r = np.arange(0,12)
# enter your code below
a = r.reshape(3,4)

a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

f) A 1 x 13 array from the following array

look into the `resize` method

In [116]:
n = np.empty(shape=(2,6))
### enter your code below

n.resize(1,13)
print(n)


[[-1.72723371e-077 -1.72723371e-077  2.96439388e-323  0.00000000e+000
   2.12199579e-314  1.33664410e+160  6.50813033e-091  5.93736837e-038
   5.41688143e-067  3.63081374e+179  3.99910963e+252  8.34404863e-309
   0.00000000e+000]]


) using the following array, create an array that consists of the same numbers but squared and in order from smallest to largest

In [264]:
n = np.array([7, 6, 9, 5, 8, 9, 6, 10, 3, 4, 3, 3, 1, 2, 5, 8, 6, 1, 6, 0])
### enter your code below
np.sort(n**2)

array([  0,   1,   1,   4,   9,   9,   9,  16,  25,  25,  36,  36,  36,
        36,  49,  64,  64,  81,  81, 100])

## Exercise 2

Produce  the array as asked

a) Create a 3x3x3 array with the numbers from 1, 27. Then slice it to produce the 3x3 array in the middle.

In [265]:
t27 = np.arange(1,27+1).reshape(3,3,3)

t27[1][:]


array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

b) Create a 3 x 3 array of random numbers. Then slice it to produce the numbers in the 2-index column.

In [257]:
rng = np.random.default_rng(0)
### enter your code below 
ramarr = rng.random((3, 3))
print(ramarr)
ramarr[0:3,2]


[[0.63696169 0.26978671 0.04097352]
 [0.01652764 0.81327024 0.91275558]
 [0.60663578 0.72949656 0.54362499]]


array([0.04097352, 0.91275558, 0.54362499])

c) Create a 3x3x3 array of zeros. Slice a 2x2 array from it and change the values to 1s. Then output the original 3x3x3 with `0`'s and `1`s

In [263]:
xerox = np.zeros((3,3,3))
print(xerox)

duox2 = xerox[:2,:2,:2]
duox2 [:] = 1


print('\n')
print(duox2)
xerox


[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]


[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]


array([[[1., 1., 0.],
        [1., 1., 0.],
        [0., 0., 0.]],

       [[1., 1., 0.],
        [1., 1., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

d) Create an array of all the numbers from 1, 27 (inclusive). Then produce a slice that outputs only the even numbers less than 14.

In [266]:
twenty27 = np.arange(27)+1
threex3 = twenty27.reshape(3,3,3)

less14 = threex3[(threex3 < 14) & (threex3 % 2 == 0)]

print('\n','Slice that outputs only the even numbers less than 14.','\n')
less14



 Slice that outputs only the even numbers less than 14. 



array([ 2,  4,  6,  8, 10, 12])

## Exercise 3

a) Create an array of all postive integers from 1 to 100.    
b) Reshape it into a 10 x 10 matrix  
c) Remove multiples (so numbers that aren't prime  
d) Output the prime numbers.  

a)

In [267]:
a = np.arange(100)+1
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

b) reshape it into a 10 x 10 matrix

In [268]:
a.reshape(10,10)
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

c) starting with 2 (until you get to sqrt(100) or 10), replace multiples of that number with 0

In [273]:
#3c is basically going through each number from 2 to 10. #and removing all its multiples (but not the number itself)

# so you can remove all the non-prime numbers from teh array. By replacing them with 0
#lets assume arrary1 is the one within the range of 1-100 and a 10x10 matrix
#check the element are divisible by 2,3,5,7 which are also the multiple of same numbers.

for v in range(2,10+1):
    a[(a != v) & (a %v == 0)] = 0
a


array([ 2,  3,  5,  7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59,
       61, 67, 71, 73, 79, 83, 89, 97])

d) Using a slice, output your prime sieve containing all of the prime numbers less than 100 (be sure to exclude 1 from your slice)

hint: the length of such slice should be `25`

In [274]:
#a[(a < 6) & (a % n == 0) ]
#1 in not a prime no so I eliminate that from the output

a = a[(a != 0) & (a != 1)]
print(a.reshape(5,5))

[[ 2  3  5  7 11]
 [13 17 19 23 29]
 [31 37 41 43 47]
 [53 59 61 67 71]
 [73 79 83 89 97]]
